export const INPUT_SEARCH = 'INPUT_SEARCH';

export const FETCH_MOVIESLIST_LOADING = 'FETCH_MOVIESLIST_LOADING';
export const FETCH_MOVIESLIST_SUCCESS = 'FETCH_MOVIESLIST_SUCCESS';
export const FETCH_MOVIESLIST_FAIL = 'FETCH_MOVIESLIST_FAIL';

export const SORTING_BY_RATING = 'SORTING_BY_RATING';
export const SORTING_BY_RELEASE_DATE = 'SORTING_BY_RELEASE_DATE';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';

export const FETCH_MOVIE_DETAILS_LOADING = 'FETCH_MOVIE_DETAILS_LOADING';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAIL = 'FETCH_MOVIE_DETAILS_FAIL';

export const DELETE_MOVIE_FROM_LIST = 'DELETE_MOVIE_FROM_LIST';
