export const moviesList = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    release_date: 1994,
    runtime: 142,
    rating: 9.3,
    genre: 'Crime, Drama',
    director: 'Frank Darabont',
    actors: 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/I/51yioWqINiL._AC_.jpg',
  },
  {
    id: 2,
    title: 'The Godfather',
    release_date: 1972,
    runtime: 175,
    rating: 9.2,
    genre: 'Crime, Drama',
    director: 'Francis Ford Coppola',
    actors: 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,704,1000_AL_.jpg',
  },
  {
    id: 3,
    title: 'The Godfather: Part II',
    release_date: 1974,
    runtime: 202,
    rating: 9.0,
    genre: 'Crime, Drama',
    director: 'Francis Ford Coppola',
    actors: 'Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
  },
  {
    id: 4,
    title: 'The Dark Knight',
    release_date: 2008,
    runtime: 152,
    rating: 9.0,
    genre: 'Action, Crime, Drama',
    director: 'Christopher Nolan',
    actors: 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
  },
  {
    id: 5,
    title: 'Kill Bill: Vol. 1',
    release_date: 2003,
    runtime: 111,
    rating: 8.8,
    genre: 'Action, Crime, Thriller',
    director: 'Quentin Tarantino',
    actors: 'Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/I/51E3De4zfaL._SX350_BO1,204,203,200_.jpg',
  },
  {
    id: 6,
    title: 'Pulp Fiction',
    release_date: 1994,
    runtime: 154,
    rating: 8.9,
    genre: 'Crime, Drama',
    director: 'Quentin Tarantino',
    actors: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
  },
  {
    id: 7,
    title: 'The Lord of the Rings: The Return of the King',
    release_date: 2003,
    runtime: 201,
    rating: 8.9,
    genre: 'Adventure, Drama, Fantasy',
    director: 'Peter Jackson',
    actors: 'Elijah Wood, Ian McKellen, Orlando Bloom, Viggo Mortensen',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/d20b35b9c0734c429b652bd0280158a8c7c0dfa1a4c2254d0312eacf4c902c32._RI_V_TTW_.jpg',
  },
  {
    id: 8,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    release_date: 2001,
    runtime: 178,
    rating: 8.8,
    genre: 'Adventure, Drama, Fantasy',
    director: 'Peter Jackson',
    actors: 'Elijah Wood, Ian McKellen, Orlando Bloom, Viggo Mortensen',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
  },
  {
    id: 9,
    title: 'Fight Club',
    release_date: 1999,
    runtime: 139,
    rating: 8.8,
    genre: 'Drama',
    director: 'David Fincher',
    actors: 'Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf',
    poster_path:
      'https://images-na.ssl-images-amazon.com/images/I/51wdlwCkp0L._SX349_BO1,204,203,200_.jpg',
  },
];
